import { useState, useEffect } from 'react'
import { SAMPLE_DOCUMENTS, STATS } from '../data/sampleData'

/**
 * Load documents from /data/documents.json (generated by extract.py)
 * Falls back to sample data if the file isn't available yet.
 */
export function useDocuments() {
  const [documents, setDocuments] = useState([])
  const [meta, setMeta] = useState(null)
  const [loading, setLoading] = useState(true)
  const [source, setSource] = useState('sample') // 'sharepoint' | 'sample'

  useEffect(() => {
    // Use BASE_URL so this works both locally (/) and on GitHub Pages (/Knowledge-Base/)
    const url = `${import.meta.env.BASE_URL}data/documents.json`
    fetch(url)
      .then((r) => {
        if (!r.ok) throw new Error('not found')
        return r.json()
      })
      .then((data) => {
        const docs = data.documents || []
        // Only use live data if it actually has documents
        if (docs.length === 0) throw new Error('empty')
        setDocuments(docs)
        setMeta({ generated: data.generated, totalDocuments: data.totalDocuments })
        setSource('sharepoint')
      })
      .catch(() => {
        setDocuments(SAMPLE_DOCUMENTS)
        setMeta({ generated: STATS.lastUpdated, totalDocuments: SAMPLE_DOCUMENTS.length })
        setSource('sample')
      })
      .finally(() => setLoading(false))
  }, [])

  const stats = {
    total: documents.length,
    byCategory: documents.reduce((acc, d) => {
      acc[d.category] = (acc[d.category] || 0) + 1
      return acc
    }, {}),
    recordings: documents.filter((d) => d.isMedia).length,
    presentations: documents.filter((d) => d.extension === '.pptx').length,
    brds: documents.filter((d) => d.category === 'BRD').length,
  }

  return { documents, meta, loading, source, stats }
}
